import pretty_errors
def fn(a, b):
    print(a // b)
def test():
    fn(2, 0)
test()